name = "NCLColors"
uuid = "dd7501f7-ffe0-47c7-a463-cd7879e87853"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
Colors = "0.12"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
